# Generated by Django 2.0 on 2017-12-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('tags', models.TextField()),
            ],
        ),
    ]
